swagger: "2.0"
info:
  description: "Cloud Endpoints DNS"
  title: "Cloud Endpoints DNS"
  version: "1.0.0"
paths: {}
host: "frontend.endpoints.am-arg-01.cloud.goog"
x-google-endpoints:
- name: "frontend.endpoints.am-arg-01.cloud.goog"
  target: "34.149.203.18"
