apiVersion: "networking.istio.io/v1alpha3"
kind: "Gateway"
metadata:
  name: "asm-ingressgateway"
spec:
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: edge2mesh-credential
